name: Manual Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: 'build/libs/QuickVoiceChat.jar'

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          draft: true
          files: build/libs/QuickVoiceChat.jar
